kind: pipeline
name: default

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: hostdir
    host:
      path: /root/project-config/baseline-node

workspace:
  path: /repo

steps:
  - name: baseline-node20-alpine
    image: docker:dind
    environment:
      DOCKER_PASS:
        from_secret: DOCKER_PASSWORD
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: hostdir
        path: /hostdir
    commands:
      - chmod +x /repo/20/baseline-node20-alpine/build.sh
      - /repo/20/baseline-node20-alpine/build.sh

  - name: baseline-node20
    image: docker:dind
    environment:
      DOCKER_PASS:
        from_secret: DOCKER_PASSWORD
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: hostdir
        path: /hostdir
    commands:
      - chmod +x /repo/20/baseline-node20/build.sh
      - /repo/20/baseline-node20/build.sh

  - name: baseline-node20-puppeteer
    image: docker:dind
    environment:
      DOCKER_PASS:
        from_secret: DOCKER_PASSWORD
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: hostdir
        path: /hostdir
    commands:
      - chmod +x /repo/20/baseline-node20-puppeteer/build.sh
      - /repo/20/baseline-node20-puppeteer/build.sh

  - name: baseline-node20-full
    image: docker:dind
    environment:
      DOCKER_PASS:
        from_secret: DOCKER_PASSWORD
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: hostdir
        path: /hostdir
    commands:
      - chmod +x /repo/20/baseline-node20-full/build.sh
      - /repo/20/baseline-node20-full/build.sh

  - name: baseline-node20-full-puppeteer
    image: docker:dind
    environment:
      DOCKER_PASS:
        from_secret: DOCKER_PASSWORD
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: hostdir
        path: /hostdir
    commands:
      - chmod +x /repo/20/baseline-node20-full-puppeteer/build.sh
      - /repo/20/baseline-node20-full-puppeteer/build.sh