name: Build and Push Docker Images

on:
  push:

jobs:
  build-node20:
    name: Node 20 images
    uses: ./.github/workflows/build-node20.yml
    secrets: inherit

  build-node22:
    name: Node 22 images
    uses: ./.github/workflows/build-node22.yml
    secrets: inherit

  build-node24:
    name: Node 24 images
    uses: ./.github/workflows/build-node24.yml
    secrets: inherit
