name: Build Node 24 Images

on:
  workflow_call:

jobs:
  build-node24:
    name: baseline-node24 (slim)
    uses: ./.github/workflows/build-image.yml
    with:
      image_name: baseline-node24 (slim)
      build_script: 24/baseline-node24/build.sh
    secrets: inherit

  build-node24-alpine:
    name: baseline-node24-alpine
    uses: ./.github/workflows/build-image.yml
    with:
      image_name: baseline-node24-alpine
      build_script: 24/baseline-node24-alpine/build.sh
    secrets: inherit

  build-node24-full:
    name: baseline-node24-full
    uses: ./.github/workflows/build-image.yml
    with:
      image_name: baseline-node24-full
      build_script: 24/baseline-node24-full/build.sh
    secrets: inherit

  build-node24-puppeteer:
    name: baseline-node24-puppeteer
    needs: build-node24
    uses: ./.github/workflows/build-image.yml
    with:
      image_name: baseline-node24-puppeteer
      build_script: 24/baseline-node24-puppeteer/build.sh
    secrets: inherit

  build-node24-full-puppeteer:
    name: baseline-node24-full-puppeteer
    needs: build-node24-full
    uses: ./.github/workflows/build-image.yml
    with:
      image_name: baseline-node24-full-puppeteer
      build_script: 24/baseline-node24-full-puppeteer/build.sh
    secrets: inherit
